ERROR - 2022-08-06 06:52:23 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 06:52:23 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 06:52:51 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 06:52:51 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 06:52:53 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 06:52:53 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 06:52:53 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 06:52:53 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 06:52:54 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 06:52:54 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 08:05:00 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 08:05:00 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 08:07:04 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 08:07:04 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 08:07:12 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 08:07:12 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-06 08:07:13 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-08-06 08:07:13 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /var/www/html/system/Database/BaseConnection.php(1387): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/system/Database/BaseConnection.php(1426): CodeIgniter\Database\BaseConnection->getFieldNames('users')
#2 /var/www/html/app/Models/Users_model.php(13): CodeIgniter\Database\BaseConnection->fieldExists('uuid_business_i...', 'users')
#3 /var/www/html/app/Controllers/Home.php(11): App\Models\Users_model->__construct()
#4 /var/www/html/system/CodeIgniter.php(802): App\Controllers\Home->__construct()
#5 /var/www/html/system/CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#6 /var/www/html/system/CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
